[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
lib_deps = 
    https://github.com/pschatzmann/ESP32-A2DP.git
    esphome/ESPAsyncWebServer-esphome @ ^3.1.0
